zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    hello-server:
      path: /server/**
      url: http://localhost:8071
      retryable: true
    hello-client:
      path: /client/**
      serviceId: HELLO-CLIENT
      retryable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost

server:
  port: 8079

ribbon:
  eureka:
    enabled: true
    ReadTimeout: 100000
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    
HELLO-CLIENT.ribbon:    
    ReadTimeout: 100000
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    
spring:
  application:
    name: zuul-service

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000